# Generated by Django 5.2.2 on 2025-07-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0004_prato_foto_prato_prato_puclicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prato',
            old_name='puclicado',
            new_name='publicado',
        ),
    ]
