# Generated by Django 5.2.2 on 2025-07-12 11:58

import churras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0005_rename_puclicado_prato_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='foto_prato',
            field=models.ImageField(blank=True, upload_to=churras.models.get_file_path),
        ),
    ]
